### PR TITLE
Create HelloWorld.whitespace

### PR DESCRIPTION
**Pull request by aniruddhaadak80**
For issue #263

### CODE REVIEW

**Comment by agnilondapakou** [comment]
This code's not printing anything.

Is it working to your place ?

**Comment by aniruddhaadak80** [comment]
> This code's not printing anything.
> 
> Is it working to your place ?

Now please try  this @agnilondapakou . Thank you .

**Review by Jossyboydgenius — COMMENTED** [review]
This is quiet confusing.

**Comment by agnilondapakou** [comment]
Exactly. The code is not printing "Hello world"

**Pull request closed without merging**
